// ===========================
// ZEN AI SERVER
// ===========================

const express = require("express");
const cors = require("cors");

const app = express();

app.use(cors());
app.use(express.json());

// ===========================
// HOME
// ===========================

app.get("/", (req, res) => {

    res.json({
        name: "ZEN AI",
        version: "1.0.0",
        status: "Online"
    });

});

// ===========================
// CHAT API
// ===========================

app.post("/api/chat", async (req, res) => {

    try {

        const { message } = req.body;

        if (!message) {

            return res.status(400).json({
                error: "Message Required"
            });

        }

        let reply = "";

        const msg = message.toLowerCase();

        if (msg.includes("halo")) {

            reply = "Halo! Saya ZEN AI 🤖";

        } else if (msg.includes("script")) {

            reply = "Saya dapat membantu membuat script.";

        } else if (msg.includes("gui")) {

            reply = "Saya dapat membantu membuat GUI.";

        } else {

            reply =
            "ZEN AI menerima pesan: " + message;

        }

        res.json({
            success: true,
            reply: reply
        });

    } catch (err) {

        res.status(500).json({
            error: err.message
        });

    }

});

// ===========================
// SCRIPT GENERATOR
// ===========================

app.post("/api/script", (req, res) => {

    const { prompt } = req.body;

    res.json({

        success: true,

        result:
`-- Generated By ZEN AI

print("Hello World")
`

    });

});

// ===========================
// GUI GENERATOR
// ===========================

app.post("/api/gui", (req, res) => {

    res.json({

        success: true,

        result: {

            name: "Modern GUI",

            style: "Dark",

            buttons: 5

        }

    });

});

// ===========================
// LOGO GENERATOR
// ===========================

app.post("/api/logo", (req, res) => {

    res.json({

        success: true,

        result:
        "Logo generation endpoint ready."

    });

});

// ===========================
// IMAGE GENERATOR
// ===========================

app.post("/api/image", (req, res) => {

    res.json({

        success: true,

        result:
        "Image generation endpoint ready."

    });

});

// ===========================
// USER PROFILE
// ===========================

app.get("/api/profile", (req, res) => {

    res.json({

        username: "ZEN USER",

        role: "Member",

        credits: 999999

    });

});

// ===========================
// START SERVER
// ===========================

const PORT =
process.env.PORT || 3000;

app.listen(PORT, () => {

    console.log(
        `ZEN AI Running On Port ${PORT}`
    );

});
